sudo: required

os:
  - linux

language: go

services:
  - docker

go:
  - master

script:
  - if [[ "$TRAVIS_BRANCH" == "$TRAVIS_TAG" ]]; then
      echo "this is a tag";
    else
      echo "this is a branch";
    fi
  - docker --version
  - go test -v $(go list ./... | grep -v /vendor/) -cover
  - go build -v
