sudo: required

os:
  - linux

language: go

services:
  - docker

go:
  - master

script:
  - docker --version
  - go test -v $(go list ./... | grep -v /vendor/) -cover
  - if [[ "$TRAVIS_BRANCH" == "$TRAVIS_TAG" ]]; then
      pip install --user awscli && 
      export PATH=$PATH:$HOME/.local/bin && 
      aws --version && 
      if [[ $TRAVIS_TAG == *"dev"* ]]; then
        docker build -t kruldev:${TRAVIS_TAG} .;
      else
        docker build -t krul:${TRAVIS_TAG} .;
      fi && 
      docker images;
    else
      go build -v;
    fi
