FROM golang

ADD . /go/src/pullr-krul
WORKDIR /go/src/pullr-krul
ARG PULLR_TAG

ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG DEV_PULLR_SNS_ARN
ARG REGION

ENV AWS_ACCESS_KEY_ID $AWS_ACCESS_KEY_ID
ENV AWS_SECRET_ACCESS_KEY $AWS_SECRET_ACCESS_KEY
ENV DEV_PULLR_SNS_ARN $DEV_PULLR_SNS_ARN
ENV REGION $REGION

RUN go generate
RUN go build -v
ENTRYPOINT ["/go/src/pullr-krul/pullr-krul"]
