FROM golang

ADD . /go/src/pullr-krul
WORKDIR /go/src/pullr-krul
ARG PULLR_TAG

ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG PULLR_SNS_ARN
ARG AWS_REGION

ENV AWS_ACCESS_KEY_ID $AWS_ACCESS_KEY_ID
ENV AWS_SECRET_ACCESS_KEY $AWS_SECRET_ACCESS_KEY
ENV PULLR_SNS_ARN $PULLR_SNS_ARN
ENV AWS_REGION $AWS_REGION

RUN go generate
RUN go build -v
ENTRYPOINT ["/go/src/pullr-krul/pullr-krul"]
